 exports.INTERESTS_LIST = [
    ["art", "Art"],
    ["books", "Books"],
    ["boardgames", "Board Games"],
    ["cardgames", "Card Games"],
    ["food", "Food"],
    ["intruments", "Instruments"],
    ["music", "Music"],
    ["movies", "Movies"],
    ["perfumery", "Perfumary"],
    ["programming", "Programming"],
    ["tvshows", "Tv Shows"],
    ["videogames", "Video Games"],
    ["other", "Other"],
]